# This is a basic workflow to help you get started with Actions

name: Build app and deploy to aliyun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 安装Node.js 根据你本地的版本号来安装，否则可能出现build异常
      - name: use Node.js 16.14.2
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: v16.14.2
      # 安装依赖
      - name: npm install
        run: |
          cd ./docs
          # 异常时尝试删除node_modules文件夹
          rm -rf ./node_modules
          npm install
      # 打包
      - name: npm build
        run: |
          cd ./docs
          npm run docs:build
      # 部署到阿里云ECS
      - name: Deploy to Aliyun ECS
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录，build生成的dist目录
          SOURCE: "./dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "123.57.38.114"
          # 用户名
          REMOTE_USER: "root"
          # 目标地址 服务器部署路径，最终会在这个路径下添加dist目录
          TARGET: "/data/web/homepage"
